export const styles = {
  wrapper: {
    position: "relative",
    width: "100%",
    height: "100%",
    "min-height": "0",
    flex: "1 1 auto",
  },
  scrollContainer: {
    width: "100%",
    height: "100%",
    "overflow-x": "auto",
    "overflow-y": "auto",
    "scrollbar-width": "none",
    "scroll-snap-type": "x mandatory",
    "scroll-behavior": "smooth",
    "&::-webkit-scrollbar": { display: "none" },
  },
  snapTarget: {
    position: "absolute",
    top: "0",
    bottom: "0",
    width: "1px",
    "scroll-snap-align": "center",
    "pointer-events": "none",
  },
  track: {
    position: "relative",
    "min-width": "100%",
  },
  baseline: {
    position: "absolute",
    top: "50%",
    right: "0",
    height: "2px",
    "background-color": "rgba(255, 255, 255, 0.25)",
  },
  yearTick: {
    position: "absolute",
    top: "calc(50% - 5px)",
    width: "1px",
    height: "10px",
    "background-color": "rgba(255, 255, 255, 0.4)",
    "pointer-events": "none",
  },
  eventWrapper: {
    position: "absolute",
    top: "0",
    bottom: "0",
    left: "0",
    right: "0",
    opacity: "0",
    transition: "opacity 400ms ease",
    "pointer-events": "none",
  },
  eventWrapperVisible: {
    opacity: "1",
  },
  card: {
    position: "absolute",
    width: "260px",
    "text-align": "center",
    display: "flex",
    "flex-direction": "column",
    gap: "6px",
    "align-items": "center",
    "@media (max-width: 600px)": {
      width: "220px",
    },
  },
  cardImage: {
    width: "120px",
    height: "120px",
    "object-fit": "cover",
    "object-position": "center",
    "border-radius": "4px",
    "flex-shrink": "0",
  },
  cardTitle: {
    margin: "0",
    color: "white",
    "font-size": "0.6em",
    "font-weight": "bold",
  },
  cardDescription: {
    margin: "0",
    color: "#bbb",
    "font-size": "0.5em",
    "line-height": "1.4",
    display: "-webkit-box",
    "-webkit-line-clamp": "3",
    "-webkit-box-orient": "vertical",
    overflow: "hidden",
  },
  stem: {
    position: "absolute",
    width: "2px",
    "background-color": "#5E1219",
  },
  rail: {
    position: "absolute",
    height: "10px",
    "border-radius": "5px",
    "background-color": "#5E1219",
    "box-shadow": "0 0 0 4px #000000",
  },
  railOngoing: {
    position: "absolute",
    height: "10px",
    "border-radius": "5px 0 0 5px",
    "background-image":
      "linear-gradient(to right, #5E1219 0%, #5E1219 75%, rgba(94, 18, 25, 0) 100%)",
  },
  rangeBar: {
    position: "absolute",
    height: "10px",
    "border-radius": "5px",
    "background-color": "#5E1219",
    "box-shadow": "0 0 0 4px #000000",
  },
  rangeBarOngoing: {
    position: "absolute",
    height: "10px",
    "border-radius": "5px 0 0 5px",
    "background-image":
      "linear-gradient(to right, #5E1219 0%, #5E1219 75%, rgba(94, 18, 25, 0) 100%)",
  },
  dot: {
    position: "absolute",
    width: "14px",
    height: "14px",
    "border-radius": "50%",
    "background-color": "#5E1219",
    "box-shadow": "0 0 0 4px #000000",
  },
  junction: {
    position: "absolute",
    width: "10px",
    height: "10px",
    "border-radius": "50%",
    "background-color": "#5E1219",
    "box-shadow": "0 0 0 3px #000000",
  },
  year: {
    position: "absolute",
    color: "white",
    "font-size": "0.5em",
    "font-weight": "bold",
    "white-space": "nowrap",
  },
  arrow: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    "z-index": "2",
    opacity: "1",
    transition: "opacity 250ms ease",
    "@media (max-width: 600px)": {
      display: "none",
    },
  },
  arrowHidden: {
    opacity: "0",
    "pointer-events": "none",
  },
  arrowLeft: { left: "-8px" },
  arrowRight: { right: "-8px" },
};
